//go:build linux

package ebpf

import (
	"github.com/cilium/ebpf"
)

// LoadConnect loads the BPF program into a CollectionSpec.
// This wraps the internal loadConnect() function generated by bpf2go.
func LoadConnect() (*ebpf.CollectionSpec, error) {
	return loadConnect()
}

// ConnectObjects wraps the generated connectObjects type.
type ConnectObjects = connectObjects

// ConnectPrograms wraps the generated connectPrograms type.
type ConnectPrograms = connectPrograms

// ConnectMaps wraps the generated connectMaps type.
type ConnectMaps = connectMaps
